# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, junit_test ]

jobs:
  test:
    name: Unit-Test

    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [windows-latest, macOs-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Maven Package
        run: cd dms && mvn -B clean package
      
      - name: Maven Test
        run: cd dms && mvn test

      - name: Jacoco Coverage
        run: cd dms && mvn clean verify

      - name: Maven Verify
        run: cd dms && mvn -B clean verify -DskipTests

      - name: Codestyle Check
        run: cd dms && mvn checkstyle:check
